# Generated by Django 5.1.3 on 2024-11-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('rasm', models.ImageField(upload_to='maxsulot/')),
            ],
        ),
    ]
