# Generated by Django 5.1.3 on 2024-11-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_maxsulot_narxi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('rasm', models.ImageField(upload_to='mahsulot/')),
            ],
        ),
    ]
