# Generated by Django 5.1.3 on 2024-11-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mahsulot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahsulot',
        ),
    ]
