# Generated by Django 5.1.3 on 2024-11-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_mahsulot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('rasmi', models.ImageField(upload_to='korinish/')),
            ],
        ),
    ]
