# Generated by Django 5.1.3 on 2024-11-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_korinish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('rasmi', models.ImageField(upload_to='xaridor/')),
            ],
        ),
    ]
